services:
  app:
    build: 
      context: ./RPGdata
      target: prod
    image: rpgzona/app:latest
    restart: unless-stopped
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      PG_ENDPOINT: postgresql://db:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rpg_sessions
      SECRET_KEY: ${SECRET_KEY}
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      ENV: production
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    # те же порты, что в dev
    ports:
      - "6601:8000"
    # без volumes — код из образа

  web-client:
    build:
      context: ./RPGWebMainClient
      target: prod
    image: rpgzona/web-client:latest
    restart: unless-stopped
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: production
    command: ["pnpm", "start"]
    depends_on:
      - app
    ports:
      - "6602:3000"
    # без volumes: /app

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rpg_sessions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6603:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pg-backup:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: rpg_sessions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_DIR: /backups
      BACKUP_COMPRESSION: gzip
      TZ: Europe/Moscow
    volumes:
      - ./backups:/backups

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "6604:9000"
      - "6605:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    volumes:
      - redis_data:/redis_data
    ports:
      - "6606:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "6607:5672"
      - "6608:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  minio_data:
  redis_data:
  rabbitmq_data:
