"""+audio

Revision ID: 00872eb53be5
Revises: c4acdad9da2a
Create Date: 2026-04-03 14:21:24.088723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00872eb53be5'
down_revision: Union[str, None] = 'c4acdad9da2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_track',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_track_created_by'), 'audio_track', ['created_by'], unique=False)
    op.create_index(op.f('ix_audio_track_id'), 'audio_track', ['id'], unique=False)
    op.create_table('scene_exposure_audio',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('audio_track_id', sa.Uuid(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('fade_in', sa.Float(), nullable=False),
    sa.Column('fade_out', sa.Float(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_track_id'], ['audio_track.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'audio_track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_exposure_audio')
    op.drop_index(op.f('ix_audio_track_id'), table_name='audio_track')
    op.drop_index(op.f('ix_audio_track_created_by'), table_name='audio_track')
    op.drop_table('audio_track')
    # ### end Alembic commands ###
