"""player character snapshot

Revision ID: 1c14e3fbcd43
Revises: e20c33a4bf2c
Create Date: 2026-05-19 13:03:15.338909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c14e3fbcd43'
down_revision: Union[str, None] = 'e20c33a4bf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('character_source_type', sa.String(), nullable=True))
    op.add_column('player', sa.Column('character_id', sa.UUID(), nullable=True))
    op.add_column('player', sa.Column('character_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'character_snapshot')
    op.drop_column('player', 'character_id')
    op.drop_column('player', 'character_source_type')
    # ### end Alembic commands ###
