"""player character snapshot

Revision ID: 247aef56aacb
Revises: 1c14e3fbcd43
Create Date: 2026-05-19 13:05:57.719724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247aef56aacb'
down_revision: Union[str, None] = '1c14e3fbcd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('player_character_id_fkey'), 'player', type_='foreignkey')
    op.drop_column('player', 'character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('player_character_id_fkey'), 'player', 'player_character', ['character_id'], ['id'])
    # ### end Alembic commands ###
