"""initial

Revision ID: 35282f446d69
Revises: 
Create Date: 2026-03-13 09:51:17.422165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35282f446d69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tg', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('can_be_master', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rule_id_str', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_id'), 'scenario', ['id'], unique=False)
    op.create_table('user_master_group',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('master_group_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['master_group_id'], ['master_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'master_group_id')
    )
    op.create_table('game_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('quest_html_mark', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_item_id'), 'game_item', ['id'], unique=False)
    op.create_table('game_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('master_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'finished_ok', 'finished_forced', name='gamesessionstatus'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_id'), 'game_session', ['id'], unique=False)
    op.create_index(op.f('ix_game_session_name'), 'game_session', ['name'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('is_shown', sa.Boolean(), nullable=True),
    sa.Column('is_start', sa.Boolean(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('map_url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('parent_location_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('master_group_scenario_access',
    sa.Column('master_group_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['master_group_id'], ['master_group.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('master_group_id', 'scenario_id')
    )
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('allowed_character_shown_json', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_id'), 'note', ['id'], unique=False)
    op.create_table('npc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_id'), 'npc', ['id'], unique=False)
    op.create_table('obstacle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obstacle_id'), 'obstacle', ['id'], unique=False)
    op.create_index(op.f('ix_obstacle_scenario_id'), 'obstacle', ['scenario_id'], unique=False)
    op.create_table('rule_template_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id_str', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', name='uq_rule_template_set_scenario_id')
    )
    op.create_index(op.f('ix_rule_template_set_id'), 'rule_template_set', ['id'], unique=False)
    op.create_index(op.f('ix_rule_template_set_rule_id_str'), 'rule_template_set', ['rule_id_str'], unique=False)
    op.create_index(op.f('ix_rule_template_set_scenario_id'), 'rule_template_set', ['scenario_id'], unique=False)
    op.create_table('story_beat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('text_for_master', sa.String(), nullable=True),
    sa.Column('text_for_players', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('parent_story_beat_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_story_beat_id'], ['story_beat.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_beat_id'), 'story_beat', ['id'], unique=False)
    op.create_index(op.f('ix_story_beat_parent_story_beat_id'), 'story_beat', ['parent_story_beat_id'], unique=False)
    op.create_index(op.f('ix_story_beat_scenario_id'), 'story_beat', ['scenario_id'], unique=False)
    op.create_table('game_time_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('note_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_time_event_id'), 'game_time_event', ['id'], unique=False)
    op.create_table('map_object_polygon',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_location_id', sa.Uuid(), nullable=True),
    sa.Column('target_location_id', sa.Uuid(), nullable=True),
    sa.Column('is_shown', sa.Boolean(), nullable=True),
    sa.Column('is_filled', sa.Boolean(), nullable=True),
    sa.Column('is_line', sa.Boolean(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('polygon_list', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_object_polygon_id'), 'map_object_polygon', ['id'], unique=False)
    op.create_table('player_character',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_character_id'), 'player_character', ['id'], unique=False)
    op.create_table('rule_character_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_set_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=True),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_set_id'], ['rule_template_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_character_template_id'), 'rule_character_template', ['id'], unique=False)
    op.create_index(op.f('ix_rule_character_template_template_set_id'), 'rule_character_template', ['template_set_id'], unique=False)
    op.create_table('rule_item_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_set_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('quest_html_mark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_set_id'], ['rule_template_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_item_template_id'), 'rule_item_template', ['id'], unique=False)
    op.create_index(op.f('ix_rule_item_template_template_set_id'), 'rule_item_template', ['template_set_id'], unique=False)
    op.create_table('rule_npc_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_set_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_for_master', sa.String(), nullable=True),
    sa.Column('description_for_players', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_set_id'], ['rule_template_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_npc_template_id'), 'rule_npc_template', ['id'], unique=False)
    op.create_index(op.f('ix_rule_npc_template_template_set_id'), 'rule_npc_template', ['template_set_id'], unique=False)
    op.create_table('scenario_template_set_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('template_set_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_set_id'], ['rule_template_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'template_set_id', name='uq_scenario_template_set_link')
    )
    op.create_index(op.f('ix_scenario_template_set_link_id'), 'scenario_template_set_link', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_template_set_link_scenario_id'), 'scenario_template_set_link', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_template_set_link_template_set_id'), 'scenario_template_set_link', ['template_set_id'], unique=False)
    op.create_table('scene_exposure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('story_beat_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(location_id IS NULL) <> (story_beat_id IS NULL)', name='scene_exposure_location_xor_story_beat'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_beat_id'], ['story_beat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_exposure_id'), 'scene_exposure', ['id'], unique=False)
    op.create_index(op.f('ix_scene_exposure_location_id'), 'scene_exposure', ['location_id'], unique=False)
    op.create_index(op.f('ix_scene_exposure_scenario_id'), 'scene_exposure', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scene_exposure_story_beat_id'), 'scene_exposure', ['story_beat_id'], unique=False)
    op.create_table('story_beat_location',
    sa.Column('story_beat_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_beat_id'], ['story_beat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_beat_id', 'location_id')
    )
    op.create_table('story_beat_npc',
    sa.Column('story_beat_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_beat_id'], ['story_beat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_beat_id', 'npc_id')
    )
    op.create_table('counter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_id'), 'counter', ['id'], unique=False)
    op.create_table('item_ownership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('npc_id', sa.Uuid(), nullable=True),
    sa.Column('owner_item_id', sa.Uuid(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('(character_id IS NOT NULL)::int + (npc_id IS NOT NULL)::int + (owner_item_id IS NOT NULL)::int = 1', name='ck_item_ownership_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['player_character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['game_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_item_id'], ['game_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', name='uq_item_ownership_item')
    )
    op.create_index(op.f('ix_item_ownership_id'), 'item_ownership', ['id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('game_session_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('finished_with_character_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['player_character.id'], ),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('rule_item_contained_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_item_template_id', sa.Uuid(), nullable=False),
    sa.Column('item_template_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_template_id'], ['rule_item_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_item_template_id'], ['rule_item_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_item_template_id', 'item_template_id', name='uq_rule_item_contained_pair')
    )
    op.create_index(op.f('ix_rule_item_contained_template_id'), 'rule_item_contained_template', ['id'], unique=False)
    op.create_index(op.f('ix_rule_item_contained_template_item_template_id'), 'rule_item_contained_template', ['item_template_id'], unique=False)
    op.create_index(op.f('ix_rule_item_contained_template_owner_item_template_id'), 'rule_item_contained_template', ['owner_item_template_id'], unique=False)
    op.create_table('rule_item_ownership_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_template_id', sa.Uuid(), nullable=False),
    sa.Column('character_template_id', sa.Uuid(), nullable=True),
    sa.Column('npc_template_id', sa.Uuid(), nullable=True),
    sa.Column('owner_item_template_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('((character_template_id IS NOT NULL)::int + (npc_template_id IS NOT NULL)::int) = 1', name='ck_rule_item_owner_exactly_one'),
    sa.ForeignKeyConstraint(['character_template_id'], ['rule_character_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_template_id'], ['rule_item_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_template_id'], ['rule_npc_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_item_template_id'], ['rule_item_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_item_ownership_template_character_template_id'), 'rule_item_ownership_template', ['character_template_id'], unique=False)
    op.create_index(op.f('ix_rule_item_ownership_template_id'), 'rule_item_ownership_template', ['id'], unique=False)
    op.create_index(op.f('ix_rule_item_ownership_template_item_template_id'), 'rule_item_ownership_template', ['item_template_id'], unique=False)
    op.create_index(op.f('ix_rule_item_ownership_template_npc_template_id'), 'rule_item_ownership_template', ['npc_template_id'], unique=False)
    op.create_index(op.f('ix_rule_item_ownership_template_owner_item_template_id'), 'rule_item_ownership_template', ['owner_item_template_id'], unique=False)
    op.create_table('scene_exposure_item',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['game_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'item_id')
    )
    op.create_table('scene_exposure_npc',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'npc_id')
    )
    op.create_table('scene_exposure_obstacle',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('obstacle_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['obstacle_id'], ['obstacle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'obstacle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_exposure_obstacle')
    op.drop_table('scene_exposure_npc')
    op.drop_table('scene_exposure_item')
    op.drop_index(op.f('ix_rule_item_ownership_template_owner_item_template_id'), table_name='rule_item_ownership_template')
    op.drop_index(op.f('ix_rule_item_ownership_template_npc_template_id'), table_name='rule_item_ownership_template')
    op.drop_index(op.f('ix_rule_item_ownership_template_item_template_id'), table_name='rule_item_ownership_template')
    op.drop_index(op.f('ix_rule_item_ownership_template_id'), table_name='rule_item_ownership_template')
    op.drop_index(op.f('ix_rule_item_ownership_template_character_template_id'), table_name='rule_item_ownership_template')
    op.drop_table('rule_item_ownership_template')
    op.drop_index(op.f('ix_rule_item_contained_template_owner_item_template_id'), table_name='rule_item_contained_template')
    op.drop_index(op.f('ix_rule_item_contained_template_item_template_id'), table_name='rule_item_contained_template')
    op.drop_index(op.f('ix_rule_item_contained_template_id'), table_name='rule_item_contained_template')
    op.drop_table('rule_item_contained_template')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_item_ownership_id'), table_name='item_ownership')
    op.drop_table('item_ownership')
    op.drop_index(op.f('ix_counter_id'), table_name='counter')
    op.drop_table('counter')
    op.drop_table('story_beat_npc')
    op.drop_table('story_beat_location')
    op.drop_index(op.f('ix_scene_exposure_story_beat_id'), table_name='scene_exposure')
    op.drop_index(op.f('ix_scene_exposure_scenario_id'), table_name='scene_exposure')
    op.drop_index(op.f('ix_scene_exposure_location_id'), table_name='scene_exposure')
    op.drop_index(op.f('ix_scene_exposure_id'), table_name='scene_exposure')
    op.drop_table('scene_exposure')
    op.drop_index(op.f('ix_scenario_template_set_link_template_set_id'), table_name='scenario_template_set_link')
    op.drop_index(op.f('ix_scenario_template_set_link_scenario_id'), table_name='scenario_template_set_link')
    op.drop_index(op.f('ix_scenario_template_set_link_id'), table_name='scenario_template_set_link')
    op.drop_table('scenario_template_set_link')
    op.drop_index(op.f('ix_rule_npc_template_template_set_id'), table_name='rule_npc_template')
    op.drop_index(op.f('ix_rule_npc_template_id'), table_name='rule_npc_template')
    op.drop_table('rule_npc_template')
    op.drop_index(op.f('ix_rule_item_template_template_set_id'), table_name='rule_item_template')
    op.drop_index(op.f('ix_rule_item_template_id'), table_name='rule_item_template')
    op.drop_table('rule_item_template')
    op.drop_index(op.f('ix_rule_character_template_template_set_id'), table_name='rule_character_template')
    op.drop_index(op.f('ix_rule_character_template_id'), table_name='rule_character_template')
    op.drop_table('rule_character_template')
    op.drop_index(op.f('ix_player_character_id'), table_name='player_character')
    op.drop_table('player_character')
    op.drop_index(op.f('ix_map_object_polygon_id'), table_name='map_object_polygon')
    op.drop_table('map_object_polygon')
    op.drop_index(op.f('ix_game_time_event_id'), table_name='game_time_event')
    op.drop_table('game_time_event')
    op.drop_index(op.f('ix_story_beat_scenario_id'), table_name='story_beat')
    op.drop_index(op.f('ix_story_beat_parent_story_beat_id'), table_name='story_beat')
    op.drop_index(op.f('ix_story_beat_id'), table_name='story_beat')
    op.drop_table('story_beat')
    op.drop_index(op.f('ix_rule_template_set_scenario_id'), table_name='rule_template_set')
    op.drop_index(op.f('ix_rule_template_set_rule_id_str'), table_name='rule_template_set')
    op.drop_index(op.f('ix_rule_template_set_id'), table_name='rule_template_set')
    op.drop_table('rule_template_set')
    op.drop_index(op.f('ix_obstacle_scenario_id'), table_name='obstacle')
    op.drop_index(op.f('ix_obstacle_id'), table_name='obstacle')
    op.drop_table('obstacle')
    op.drop_index(op.f('ix_npc_id'), table_name='npc')
    op.drop_table('npc')
    op.drop_index(op.f('ix_note_id'), table_name='note')
    op.drop_table('note')
    op.drop_table('master_group_scenario_access')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_game_session_name'), table_name='game_session')
    op.drop_index(op.f('ix_game_session_id'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_game_item_id'), table_name='game_item')
    op.drop_table('game_item')
    op.drop_table('user_master_group')
    op.drop_index(op.f('ix_scenario_id'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('master_group')
    # ### end Alembic commands ###
