"""player character snapshot

Revision ID: 73974522f0c1
Revises: 247aef56aacb
Create Date: 2026-05-19 13:14:35.002764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73974522f0c1'
down_revision: Union[str, None] = '247aef56aacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('character_id', sa.UUID(), nullable=True))
    op.drop_column('player', 'character_source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('character_source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('player', 'character_id')
    # ### end Alembic commands ###
