"""clm name fix

Revision ID: 8c280fda31d9
Revises: 2fa36ba1c346
Create Date: 2026-05-05 14:29:15.510691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c280fda31d9'
down_revision: Union[str, None] = '2fa36ba1c346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('extra_images', sa.JSON(), nullable=True))
    op.drop_column('location', 'images_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('images_path', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('location', 'extra_images')
    # ### end Alembic commands ###
