"""templates to exposures

Revision ID: 8ee42590bb5e
Revises: 3474aadb9af9
Create Date: 2026-03-26 12:35:21.701642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ee42590bb5e'
down_revision: Union[str, None] = '3474aadb9af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_exposure_template_item',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('template_item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_item_id'], ['rule_item_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'template_item_id')
    )
    op.create_table('scene_exposure_template_npc',
    sa.Column('scene_exposure_id', sa.Uuid(), nullable=False),
    sa.Column('template_npc_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scene_exposure_id'], ['scene_exposure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_npc_id'], ['rule_npc_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scene_exposure_id', 'template_npc_id')
    )
    op.drop_index(op.f('ix_on_use_item_id'), table_name='on_use_item')
    op.drop_table('on_use_item')
    op.drop_index(op.f('ix_requirement_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_player_action_id'), table_name='player_action')
    op.drop_table('player_action')
    op.drop_index(op.f('ix_game_item_scheme_id'), table_name='game_item_scheme')
    op.drop_table('game_item_scheme')
    op.drop_table('where_object')
    op.drop_index(op.f('ix_stat_id'), table_name='stat')
    op.drop_table('stat')
    op.drop_index(op.f('ix_body_id'), table_name='body')
    op.drop_table('body')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_skill_group_id'), table_name='skill_group')
    op.drop_table('skill_group')
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_action',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description_for_master', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_for_players', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('add_time_secs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('riggers_note_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('npc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item_scheme_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(\nCASE\n    WHEN location_id IS NOT NULL THEN 1\n    ELSE 0\nEND +\nCASE\n    WHEN npc_id IS NOT NULL THEN 1\n    ELSE 0\nEND +\nCASE\n    WHEN item_scheme_id IS NOT NULL THEN 1\n    ELSE 0\nEND +\nCASE\n    WHEN item_id IS NOT NULL THEN 1\n    ELSE 0\nEND) = 1', name='only_one_fk_not_null'),
    sa.ForeignKeyConstraint(['item_id'], ['game_item.id'], name='player_action_item_id_fkey'),
    sa.ForeignKeyConstraint(['item_scheme_id'], ['game_item_scheme.id'], name='player_action_item_scheme_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='player_action_location_id_fkey'),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], name='player_action_npc_id_fkey'),
    sa.ForeignKeyConstraint(['riggers_note_id'], ['note.id'], name='player_action_riggers_note_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_action_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_player_action_id'), 'player_action', ['id'], unique=False)
    op.create_table('stat',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('init_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], name=op.f('stat_body_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('stat_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stat_pkey'))
    )
    op.create_index(op.f('ix_stat_id'), 'stat', ['id'], unique=False)
    op.create_table('on_use_item',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('init_value_change', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_change', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_new', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item_scheme_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['game_item.id'], name=op.f('on_use_item_item_id_fkey')),
    sa.ForeignKeyConstraint(['item_scheme_id'], ['game_item_scheme.id'], name=op.f('on_use_item_item_scheme_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('on_use_item_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('on_use_item_pkey'))
    )
    op.create_index(op.f('ix_on_use_item_id'), 'on_use_item', ['id'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['player_action.id'], name=op.f('requirement_action_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('requirement_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('requirement_pkey'))
    )
    op.create_index(op.f('ix_requirement_id'), 'requirement', ['id'], unique=False)
    op.create_table('where_object',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('npc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('where_object_location_id_fkey')),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], name=op.f('where_object_npc_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('where_object_pkey')),
    sa.UniqueConstraint('npc_id', 'location_id', name=op.f('_npc_location_uc'))
    )
    op.create_table('rule',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    op.create_table('skill_group',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('relative_value_shown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('rules_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rules_id'], ['rule.id'], name='skill_group_rules_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='skill_group_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_skill_group_id'), 'skill_group', ['id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('relative_value_shown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['skill_group.id'], name=op.f('skill_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_pkey'))
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('game_item_scheme',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description_for_master', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_for_players', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('erase_on_use', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('rules_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rules_id'], ['rule.id'], name=op.f('game_item_scheme_rules_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('game_item_scheme_pkey'))
    )
    op.create_index(op.f('ix_game_item_scheme_id'), 'game_item_scheme', ['id'], unique=False)
    op.create_table('body',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icon_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('img_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('rules_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rules_id'], ['rule.id'], name=op.f('body_rules_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('body_pkey'))
    )
    op.create_index(op.f('ix_body_id'), 'body', ['id'], unique=False)
    op.drop_table('scene_exposure_template_npc')
    op.drop_table('scene_exposure_template_item')
    # ### end Alembic commands ###
