"""+ equipped

Revision ID: 94f5d2dec9c7
Revises: 00872eb53be5
Create Date: 2026-04-27 12:39:41.014543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f5d2dec9c7'
down_revision: Union[str, None] = '00872eb53be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_ownership', sa.Column('equipped', sa.Boolean(), nullable=False))
    op.add_column('rule_item_ownership_template', sa.Column('equipped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_item_ownership_template', 'equipped')
    op.drop_column('item_ownership', 'equipped')
    # ### end Alembic commands ###
