"""scenario time

Revision ID: c6f55edaf1e4
Revises: ff8ab127d3f6
Create Date: 2026-06-05 08:11:56.196764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f55edaf1e4'
down_revision: Union[str, None] = 'ff8ab127d3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('scenario_starts_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'scenario_starts_at')
    # ### end Alembic commands ###
