"""clm map polygon + internal_id

Revision ID: e20c33a4bf2c
Revises: 8c280fda31d9
Create Date: 2026-05-06 16:24:20.836189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20c33a4bf2c'
down_revision: Union[str, None] = '8c280fda31d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_object_polygon', sa.Column('internal_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_object_polygon', 'internal_id')
    # ### end Alembic commands ###
