"""application session source

Revision ID: ff8ab127d3f6
Revises: 73974522f0c1
Create Date: 2026-05-19 13:42:29.662234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8ab127d3f6'
down_revision: Union[str, None] = '73974522f0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_application', sa.Column('source_kind', sa.String(), nullable=True))
    op.add_column('character_application', sa.Column('source_session_id', sa.Uuid(), nullable=True))
    op.add_column('character_application', sa.Column('source_player_id', sa.Uuid(), nullable=True))
    op.add_column('character_application', sa.Column('is_result_snapshot', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.create_foreign_key(None, 'character_application', 'player', ['source_player_id'], ['id'])
    op.create_foreign_key(None, 'character_application', 'game_session', ['source_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_application', type_='foreignkey')
    op.drop_constraint(None, 'character_application', type_='foreignkey')
    op.drop_column('character_application', 'is_result_snapshot')
    op.drop_column('character_application', 'source_player_id')
    op.drop_column('character_application', 'source_session_id')
    op.drop_column('character_application', 'source_kind')
    # ### end Alembic commands ###
