from __future__ import annotations
from plugins.pbta.base.backend.types import Move, Playbook
from ..multiclass_options import MULTICLASS_EFFECT_TEXT, MULTICLASS_MOVE_PLACEHOLDERS


thief = Playbook(
    id="thief",
    title="Вор",
    archetype="rogue",
    summary=(
        "Ты — специалист по замкам, теням, обману и первому удару. "
        "Там, где другие видят дверь, ты видишь вход; где другие видят стражу, ты видишь бреши."
    ),
    base_hp=6,
    base_load=9,
    damage_die="d8",
    starting_moves=[
        "thief_tricks_of_the_trade",
        "thief_supple_hands",
        "thief_backstab",
        "thief_flexible_morals",
        "thief_poisoner",
    ],
    advanced_moves=[
        "thief_underhanded_strike",
        "thief_caution",
        "thief_shoot_first",
        "thief_master_poisoner",
        "thief_envenom",
        "thief_brewer",
        "thief_lucky_bastard",
        "thief_useful_contacts",
        "thief_multiclass_dabbler",
        "thief_taste_for_luxury",
    ],
    advanced_moves_6_10=[
        "thief_dirty_fighting",
        "thief_huge_caution",
        "thief_alchemist",
        "thief_very_lucky_bastard",
        "thief_dodge_and_weave",
        "thief_steady_hand",
        "thief_escape_route",
        "thief_disguise",
        "thief_heist",
    ],
)


thief_moves: list[Move] = [
    Move(
        id="thief_tricks_of_the_trade",
        title="Специалист по ловушкам",
        kind="class",
        available_stats=["dex"],
        summary="Исследуешь опасное место и получаешь запас.",
        trigger="Когда вы внимательно исследуете опасное место...",
        effect=(
            "Брось +DEX."
            "Пока вы исследуете местность, вы можете потратить запас, чтобы задать следующие вопросы:"
            "• Есть ли здесь ловушка и что заставит её сработать?"
            "• Что сделает ловушка, если сработает?"
            "• Что еще интересного тут спрятано?"
        ),
        effect_10_plus="Получите запас 3.",
        effect_7_9="Получите запас 1.",
        effect_6_minus="Мастер делает ход.",
    ),
    Move(
        id="thief_supple_hands",
        title="Ловкость рук",
        kind="class",
        available_stats=["dex"],
        summary="Карман или ловушка — ваше ремесло.",
        trigger="Когда вы лезете в чужой карман или обезвреживаете ловушку...",
        effect="Брось +DEX.",
        effect_10_plus="У вас всё получается.",
        effect_7_9=(
            "но вы либо вызываете подозрения, либо подвергаетесь опасности, либо должны пожертвовать чем-то. "
            "Ведущий назовёт два последствия; выберите одно."
        ),
        effect_6_minus="Мастер делает ход.",
    ),
    Move(
        id="thief_backstab",
        title="Удар в спину",
        kind="class",
        available_stats=["dex"],
        summary="Атака по беззащитному или застигнутому врасплох врагу.",
        trigger="Когда вы атакуете в ближнем бою беззащитного или застигнутого врасплох врага...",
        effect="Можете нанести урон как обычно или бросить +DEX.",
        effect_10_plus="Выберите два: противник не связывает вас ближним боем; +1d6 урона; +1 вперёд себе или союзнику; −1 к броне цели до починки.",
        effect_7_9="Выберите одно из того же списка.",
        effect_6_minus="Мастер делает ход.",
    ),
    Move(
        id="thief_flexible_morals",
        title="Гибкая мораль",
        kind="class",
        available_stats=[],
        requires_roll=False,
        summary="Мировоззрение — вопрос формулировки.",
        trigger="",
        effect="Когда кто-то определяет ваше мировоззрение, можете назвать любое.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_poisoner",
        title="Отравитель",
        kind="class",
        available_stats=[],
        requires_roll=False,
        summary="Яды и три дозы на первом уровне.",
        trigger="",
        effect=(
            "Выберите один яд из списка в книге правил: используете его без вреда для себя "
            "и получаете три дозы. При времени и безопасном месте можете сварить 3 дозы бесплатно."
        ),
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_underhanded_strike",
        title="Подлый удар",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="+1d6 к урону удара в спину с рукой/точным оружием.",
        trigger="",
        effect="Если вы используете оружие с дальностью рука или свойством точное, удар в спину получает бонус +1d6 к урону.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_caution",
        title="Осторожность",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Дополнительный запас при работе с ловушками.",
        trigger="",
        effect="Когда вы занимаетесь ловушками, всегда получаете 1 запас дополнительно, даже на 6−.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_taste_for_luxury",
        title="Вкус к роскоши",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Хвастаясь самой ценной из своих вещей.",
        trigger="",
        effect="Хвастаясь самой ценной из своих вещей, выберите кого-то из наблюдателей. Он сделает всё, чтобы заполучить вашу вещь или похожую.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_shoot_first",
        title="Первый выстрел",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Действуете первым при внезапной атаке.",
        trigger="",
        effect="Вас не застать врасплох: даже когда враг нападает неожиданно, вы действуете первым.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_master_poisoner",
        title="Мастер-отравитель",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Повторное использование яда без риска.",
        trigger="",
        effect="Применив яд однажды, не подвергаете себя риску при повторном использовании и добавляете его к числу известных ядов.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_envenom",
        title="Отравить",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Яд для приёма внутрь можно нанести на клинок.",
        trigger="",
        effect="Вы заставите капризный яд работать; яды для приёма внутрь можно нанести на клинок без потери эффекта.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_brewer",
        title="Зельевар",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Три дозы знакомого яда.",
        trigger="",
        effect="При времени и безопасном месте можете создать три дозы яда, которым пользовались раньше.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_lucky_bastard",
        title="Везучий гадёныш",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="+1 к броне при численном превосходстве врагов.",
        trigger="",
        effect="Когда противники превосходят вас числом, вы получаете +1 к броне.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_useful_contacts",
        title="Полезные связи",
        kind="advanced",
        available_stats=["cha"],
        summary="Просьба к местному преступному миру.",
        trigger="Когда вы просите о чём-то представителей местного преступного мира...",
        effect="Брось +CHA.",
        effect_10_plus="Кто-то готов вас выручить.",
        effect_7_9="Придётся обойтись похожим или останется должок.",
        effect_6_minus="Мастер делает ход.",
    ),
    Move(
        id="thief_dirty_fighting",
        title="Грязная драка",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Заменяет: Подлый удар.",
        trigger="",
        effect="Удар в спину (рука/точное): +1d8; другие атаки — +1d4.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_huge_caution",
        title="Огромная осторожность",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Заменяет: Осторожность.",
        trigger="",
        effect="При ловушках всегда +1 запас, даже на 6−; на 12+ — запас 3 и подсказка о ловушке впереди.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_alchemist",
        title="Алхимик",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Заменяет: Зельевар.",
        trigger="",
        effect="Создаёте три дозы знакомого яда или описываете новый — мастер поставит условия.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_very_lucky_bastard",
        title="Очень везучий гадёныш",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Заменяет: Везучий гадёныш.",
        trigger="",
        effect="+1 к броне; при численном превосходстве врагов бонус +2.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_dodge_and_weave",
        title="Уклонение",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="На 12+ при побеге — с блеском.",
        trigger="",
        effect="Если при спасении от угрозы получаете 12+, делаете это с блеском — мастер даст преимущество.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_steady_hand",
        title="Твёрдая рука, острый глаз",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Метание оружия ближнего боя.",
        trigger="",
        effect="Можете метнуть оружие ближнего боя; на 7–9 не можете тратить боезапас.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_escape_route",
        title="Пути отхода",
        kind="advanced",
        available_stats=["dex"],
        summary="Побег из гущи событий.",
        trigger="Когда пора уносить ноги, назовите путь отхода и бросьте +DEX.",
        effect="",
        effect_10_plus="Благополучно сбегаете.",
        effect_7_9="Побег чего-то стоит — мастер скажет что.",
        effect_6_minus="Мастер делает ход.",
    ),
    Move(
        id="thief_disguise",
        title="Маскировка",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Замаскироваться под существо вашей комплекции.",
        trigger="",
        effect="При времени и материалах можете замаскироваться; лицо не выдаст, действия могут.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_heist",
        title="Ограбление",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Планирование кражи с вопросами мастеру.",
        trigger="Когда вы тщательно планируете кражу...",
        effect="Назовите цели и задайте вопросы из книги; при действии по ответам все получают +1 на следующий ход.",
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
    ),
    Move(
        id="thief_multiclass_dabbler",
        title="Мультикласс: дилетант",
        kind="advanced",
        available_stats=[],
        requires_roll=False,
        summary="Ты подцепил полезный чужой трюк.",
        trigger="",
        effect=MULTICLASS_EFFECT_TEXT,
        effect_10_plus="",
        effect_7_9="",
        effect_6_minus="",
        placeholders=list(MULTICLASS_MOVE_PLACEHOLDERS),
    ),
]
