# Generated by Django 5.2 on 2025-04-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='leads_to',
            new_name='leads_to_id',
        ),
        migrations.RenameField(
            model_name='mapobjectpolygon',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='mapobjectpolygon',
            old_name='map',
            new_name='map_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='action',
            new_name='action_id',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='map',
            new_name='map_id',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='character',
            new_name='character_id',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='skill',
            new_name='skill_id',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='game_item',
            new_name='game_item_id',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='npc',
            new_name='npc_id',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='player',
            new_name='player_id',
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('character_id', 'skill_id')},
        ),
    ]
