# Generated by Django 5.2 on 2025-04-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_rename_leads_to_location_leads_to_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='leads_to_id',
            new_name='leads_to',
        ),
        migrations.RenameField(
            model_name='mapobjectpolygon',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='mapobjectpolygon',
            old_name='map_id',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='action_id',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='skill_ids_json',
            new_name='skills_json',
        ),
        migrations.RenameField(
            model_name='playeraction',
            old_name='need_game_item_ids_json',
            new_name='need_game_items_json',
        ),
        migrations.RenameField(
            model_name='playeraction',
            old_name='need_skill_ids_conditions_json',
            new_name='need_skills_conditions_json',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='map_id',
            new_name='map',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='character_id',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='game_item_id',
            new_name='game_item',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='npc_id',
            new_name='npc',
        ),
        migrations.RenameField(
            model_name='whereobject',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('character', 'skill')},
        ),
    ]
