# Generated by Django 5.2 on 2025-04-15 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game_manager', '0003_rename_leads_to_id_location_leads_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='skills_json',
        ),
        migrations.RemoveField(
            model_name='playeraction',
            name='need_skills_conditions_json',
        ),
        migrations.CreateModel(
            name='StatHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название набора')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Набор навыков',
                'verbose_name_plural': 'Наборы навыков',
            },
        ),
        migrations.CreateModel(
            name='StatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.IntegerField(default=0, verbose_name='Начальное значение')),
                ('current_value', models.IntegerField(default=0, verbose_name='Текущее значение')),
                ('is_requirement', models.BooleanField(default=False, verbose_name='Является требованием')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.skill', verbose_name='Навык')),
                ('stat_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_values', to='game_manager.statholder')),
            ],
            options={
                'verbose_name': 'Значение навыка',
                'verbose_name_plural': 'Значения навыков',
                'unique_together': {('stat_holder', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
