# Generated by Django 5.2 on 2025-04-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0004_remove_npc_skills_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statholder',
            name='object_id',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='stats',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game_manager.statholder', verbose_name='Навыки'),
            preserve_default=False,
        ),
    ]
