# Generated by Django 5.2 on 2025-04-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0005_remove_statholder_object_id_playercharacter_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statholder',
            name='content_type',
        ),
    ]
