# Generated by Django 5.2 on 2025-04-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0006_remove_statholder_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercharacter',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game_manager.statholder', verbose_name='Навыки'),
        ),
    ]
